# Offense count: 30
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/BooleanSymbol:
  Exclude:
    - 'lib/puppet/type/ini_setting.rb'
    - 'lib/puppet/type/ini_subsetting.rb'
    - 'lib/puppet/util/setting_value.rb'

# # Offense count: 1
# # Configuration parameters: IgnoreLiteralBranches, IgnoreConstantBranches.
# Lint/DuplicateBranch:
#   Exclude:
#     - 'lib/puppet/util/setting_value.rb'

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
Lint/RedundantCopEnableDirective:
  Exclude:
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/type/ini_setting_spec.rb'
    - 'spec/unit/puppet/util/ini_file_spec.rb'

# Offense count: 11
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 48

# Offense count: 8
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 128

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 211

# Offense count: 3
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 18

# Offense count: 13
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 33

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  MaxOptionalParameters: 5
  Max: 6

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 20

# Offense count: 1
Naming/AccessorMethodName:
  Exclude:
    - 'lib/puppet/util/setting_value.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: lowercase, uppercase
Naming/HeredocDelimiterCase:
  Exclude:
    - 'lib/puppet/type/ini_subsetting.rb'

# Offense count: 114
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?i-mx:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'lib/puppet/type/ini_subsetting.rb'
    - 'spec/acceptance/ini_setting_spec.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/inheritance_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/provider/ini_subsetting/ruby_spec.rb'
    - 'spec/unit/puppet/util/ini_file_spec.rb'

# Offense count: 1
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: as, at, by, cc, db, id, if, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Exclude:
    - 'lib/puppet/util/ini_file.rb'

# Offense count: 2
# Configuration parameters: MinSize.
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'spec/unit/puppet/type/ini_setting_spec.rb'

# Offense count: 8
# This cop supports unsafe autocorrection (--autocorrect-all).
RSpec/BeEq:
  Exclude:
    - 'spec/spec_helper_local.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/util/ini_file_spec.rb'
    - 'spec/unit/puppet/util/setting_value_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
RSpec/ContextMethod:
  Exclude:
    - 'spec/unit/puppet/util/external_iterator_spec.rb'

# Offense count: 27
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Exclude:
    - 'spec/acceptance/ini_setting_spec.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/classes/create_multiple_ini_settings_spec.rb'
    - 'spec/unit/puppet/type/ini_setting_spec.rb'
    - 'spec/unit/puppet/type/ini_subetting_spec.rb'
    - 'spec/unit/puppet/util/external_iterator_spec.rb'
    - 'spec/unit/puppet/util/ini_file_spec.rb'

# Offense count: 12
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
    - '**/spec/routing/**/*'
    - '**/spec/system/**/*'
    - '**/spec/views/**/*'
    - 'spec/acceptance/ini_setting_spec.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/classes/create_ini_settings_test_spec.rb'
    - 'spec/classes/create_multiple_ini_settings_spec.rb'
    - 'spec/classes/inherit_test1_spec.rb'
    - 'spec/functions/create_ini_settings_spec.rb'
    - 'spec/functions/inifile_create_ini_settings_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/inheritance_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/provider/ini_subsetting/ruby_spec.rb'
    - 'spec/unit/puppet/type/ini_setting_spec.rb'
    - 'spec/unit/puppet/type/ini_subetting_spec.rb'

# Offense count: 40
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterExample:
  Exclude:
    - 'spec/acceptance/ini_setting_spec.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/classes/create_ini_settings_test_spec.rb'
    - 'spec/classes/create_multiple_ini_settings_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/type/ini_setting_spec.rb'
    - 'spec/unit/puppet/type/ini_subetting_spec.rb'
    - 'spec/unit/puppet/util/ini_file_spec.rb'
    - 'spec/unit/puppet/util/setting_value_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/EmptyLineAfterExampleGroup:
  Exclude:
    - 'spec/unit/puppet/util/setting_value_spec.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterHook:
  Exclude:
    - 'spec/acceptance/ini_setting_spec.rb'
    - 'spec/unit/puppet/type/ini_setting_spec.rb'
    - 'spec/unit/puppet/type/ini_subetting_spec.rb'

# Offense count: 8
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 26

# Offense count: 3
RSpec/ExpectInHook:
  Enabled: false

# Offense count: 12
RSpec/ImplicitBlockExpectation:
  Exclude:
    - 'spec/unit/puppet/type/ini_setting_spec.rb'
    - 'spec/unit/puppet/type/ini_subetting_spec.rb'

# Offense count: 7
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: single_line_only, single_statement_only, disallow, require_implicit
RSpec/ImplicitSubject:
  Exclude:
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/classes/create_ini_settings_test_spec.rb'
    - 'spec/classes/create_multiple_ini_settings_spec.rb'
    - 'spec/classes/inherit_test1_spec.rb'

# Offense count: 4
RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/unit/puppet/util/setting_value_spec.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
RSpec/MatchArray:
  Exclude:
    - 'spec/unit/puppet/util/ini_file_spec.rb'

# Offense count: 5
RSpec/MultipleExpectations:
  Max: 4

# Offense count: 29
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 6

# Offense count: 12
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/ini_setting_spec.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/inheritance_spec.rb'
    - 'spec/unit/puppet/provider/ini_subsetting/ruby_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/ReceiveCounts:
  Exclude:
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: and_return, block
RSpec/ReturnFromStub:
  Exclude:
    - 'spec/unit/puppet/util/ini_file_spec.rb'

# Offense count: 1
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: .
# SupportedStyles: constant, string
RSpec/VerifiedDoubleReference:
  EnforcedStyle: string

# Offense count: 4
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/puppet/util/external_iterator.rb'
    - 'lib/puppet/util/ini_file.rb'
    - 'lib/puppet/util/ini_file/section.rb'
    - 'lib/puppet/util/setting_value.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/EachForSimpleLoop:
  Exclude:
    - 'spec/unit/puppet/util/external_iterator_spec.rb'

# Offense count: 5
# This cop supports safe autocorrection (--autocorrect).
Style/ExpandPathArguments:
  Exclude:
    - 'lib/puppet/provider/ini_setting/ruby.rb'
    - 'lib/puppet/provider/ini_subsetting/ruby.rb'
    - 'lib/puppet/util/ini_file.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
Style/FileWrite:
  Exclude:
    - 'spec/unit/puppet/provider/ini_setting/inheritance_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/provider/ini_subsetting/ruby_spec.rb'

# Offense count: 10
# This cop supports safe autocorrection (--autocorrect).
Style/IfUnlessModifier:
  Exclude:
    - 'lib/puppet/type/ini_setting.rb'
    - 'lib/puppet/type/ini_subsetting.rb'
    - 'lib/puppet/util/ini_file.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/NegatedIfElseCondition:
  Exclude:
    - 'lib/puppet/util/setting_value.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantStringEscape:
  Exclude:
    - 'spec/acceptance/ini_setting_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: ConvertCodeThatCanStartToReturnNil, AllowedMethods, MaxChainLength.
# AllowedMethods: present?, blank?, presence, try, try!
Style/SafeNavigation:
  Exclude:
    - 'lib/puppet/util/ini_file.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/SlicingWithRange:
  Exclude:
    - 'lib/puppet/util/setting_value.rb'

# Offense count: 7
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/puppet/type/ini_setting.rb'
    - 'lib/puppet/type/ini_subsetting.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/util/setting_value_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowMethodsWithArguments, AllowedMethods, AllowedPatterns, AllowComments.
# AllowedMethods: define_method
Style/SymbolProc:
  Exclude:
    - 'lib/puppet/util/setting_value.rb'

# Offense count: 15
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'lib/puppet/functions/inifile/create_ini_settings.rb'
    - 'lib/puppet/util/ini_file.rb'
    - 'spec/acceptance/ini_subsetting_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/unit/puppet/provider/ini_setting/ruby_spec.rb'
    - 'spec/unit/puppet/provider/ini_subsetting/ruby_spec.rb'
